### ISSUE TITLE
Allow drag-copy of URL (currently it drags the entire window)

### ISSUE THREAD

**Issue by attilaaf** [interplanaria/bottle#13]
Clicking and dragging the URL bar does not highlight the URL but instead drags the entire window.

Expected:

User should be able to drag-copy the URL

Actual:

The user is unable to drag-copy the URL and instead the entire window is dragged

http://g.recordit.co/b85lM0GF02.gif

**Comment by MonkoftheFunk** [comment]
Maybe should  auto select all, since you wouldn't initially select a partial, and their long.
