### ISSUE TITLE
Self closing tags should work with both > and />

### ISSUE THREAD

**Issue by unwriter** [interplanaria/bottle#22]
a Meta tag that doesn't close with `/>` is failing. This shouldn't happen.

c://dae2bf6beda6ad5c70336fd02170f8ec13427b08d0890152ee1b0dd4e5e0a715

<img width="696" alt="s" src="https://user-images.githubusercontent.com/38574328/56247756-ddc9b480-6073-11e9-8995-6049999fbf4f.png">

**Comment by kevinejohn** [comment]
The issue was from the response header `content-type` being `application/xml` instead of `text/html`

Fixed: https://github.com/unwriter/c/pull/4
