### ISSUE TITLE
async script error

### ISSUE THREAD

**Issue by unwriter** [interplanaria/bottle#23]
It fails to render if a script tag is declared async.

c://ab50f2f3a3ef200bcb3826dd79902c093a0fa9aac0d07a5623ffbc8ff3691fca

<img width="1124" alt="Screen Shot 2019-04-16 at 5 13 24 PM" src="https://user-images.githubusercontent.com/38574328/56247798-09e53580-6074-11e9-9309-eb957ce149a6.png">

**Comment by kevinejohn** [comment]
The issue was from the response header `content-type` being `application/xml` instead of `text/html`

Fixed: https://github.com/unwriter/c/pull/4
